### ISSUE TITLE
Accessibility in the HTML 

### ISSUE THREAD

**Issue by boi87** [fac-15/CC#34]
The HTML reader is showing Untitled Articles and Untitled sections :rage2:

The rest looks amazing guys!! :neckbeard: 
Love the green theme. :heart_eyes:

**Comment by martingaston** [comment]
Just to add, the accessibility ratio of your foreground text and background is 2.53:1 on the WebAIM scale thingy. But, again, I completely agree - I think it looks fantastic.

**Comment by mr-bagglesworth** [comment]
These should both be covered by my next commit. Colour checking may need revising however, background alpha value getting lightened to remedy the contrast of green on green.
