### ISSUE TITLE
very small niggles

### ISSUE THREAD

**Issue by susanX** [fac-15/CC#36]
The element a must not appear as a descendant of the button element.

The aria-labelledby attribute must point to an element in the same document.

Bad value https://fonts.googleapis.com/css?family=Asap|Charmonman for attribute href on element link: Illegal character in query: | is not allowed.

The element a must not appear as a descendant of the button element.

 The aria-labelledby attribute must point to an element in the same document.

**Comment by martingaston** [comment]
I think the W3C validator *also* throws a wobbler when you reverse `a` and `button`, too :joy:

**Comment by mr-bagglesworth** [comment]
These will be covered by my next commit.
